# Generated by Django 4.0.4 on 2022-05-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLogin',
            fields=[
                ('username', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('eventdate', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('cname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('uname', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('phoneno', models.CharField(max_length=200)),
                ('fname', models.CharField(max_length=200)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tenth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('twelth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('colname', models.CharField(max_length=200)),
                ('resume', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
