# Generated by Django 4.0.4 on 2022-05-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLogin',
            fields=[
                ('username', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
            ],
        ),
    ]
