# Generated by Django 4.0.4 on 2022-05-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='highlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visiting', models.CharField(max_length=200)),
                ('highest', models.CharField(max_length=20)),
                ('average', models.CharField(max_length=20)),
                ('placement', models.CharField(max_length=20)),
            ],
        ),
    ]
