# Generated by Django 4.0.4 on 2022-05-31 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_app', '0002_highlights'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='highlights',
            new_name='highlight',
        ),
    ]
