# Generated by Django 4.0.4 on 2022-05-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_app', '0003_rename_highlights_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('cs', models.CharField(max_length=20)),
                ('it', models.CharField(max_length=20)),
                ('extc', models.CharField(max_length=20)),
            ],
        ),
    ]
