# Generated by Django 4.0.4 on 2022-06-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_app', '0005_stat_delete_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='report',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
