# Generated by Django 4.0.4 on 2022-05-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_app', '0005_companyinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='colname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='fname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='tenth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='twelth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='cname',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='uname',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='uname',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
