# Generated by Django 4.0.4 on 2022-06-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_app', '0006_stat_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='company_visited',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
