# Generated by Django 4.0.4 on 2022-05-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('username', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('application', models.CharField(default='yes', max_length=10)),
                ('date', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=200)),
                ('brochure', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
