# Generated by Django 4.0.4 on 2022-05-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedInfo',
            fields=[
                ('username', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=200)),
                ('selected', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
