# Generated by Django 4.0.4 on 2022-05-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_selectedinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedinfo',
            name='cname',
        ),
    ]
